export const menuItems = [
    {id: 'burger-fries', name: 'Burger and Fries', price: '$20.00', image: '/images/burger-fries.jpeg', description: "THINK OF THIS: 100% beef smashed on the grill and paired with a potato that's like the taste of heaven for your taste buds. Something you've never had. Something you'll never forget. That's what you get with our awesome burger and fries combination that's designed with the top down."},
    {id: 'elvis-sandwich', name: 'Elvis Sandwich', price: '$15.00', image: '/images/elvis-sandwich.jpg', desccription: "Our bakers are famous for their sandwiches! What's more is they pack an Elvis-sized P.B.J. into each one. Ask for one and you'll be treated to a sensational peanut butter and banana sandwich on our assorted breads, just how the King would have asked for it."},
    {id: 'vegan-burger', name: 'Vegan Burger', price: '$15.00', image: '/images/vegan-burger.jpg', description: "It’s a new era in veggie burgers. VegeBurger is our all-veggie, gluten-free, and vegan burger. Made and certified according to European Organic Standards to be free from artificial ingredients and preservatives. It’s the perfect companion for your high-protein meal."},
    {id: 'lamb-chops', name: 'Lamb Chops', price: '$20.00', image: '/images/lamb-chops.jpg', description: "Our fresh, herb-infused lamb chops are seasoned and marinated with our exclusive blend of secret herbs and spices and grilled to perfection to create a juicy, flavourful experience."},
    {id: 'ribeye-steak', name: 'Ribeye Steak', price: '$20.00', image: '/images/ribeye.jpg', description: "Never hungry again with the rib-eye steak. Made from fresh beef, secret herbs and spices, the rib-eye steak lets you eat without guilt."},
    {id: 'veggie-salad', name: 'Veggie Salad', price: '$10.00', image: '/images/veggie-salad.jpg', description: "Fresh green lettuce, cucumbers, golden carrot shavings, purple cabbage, and ourcrispy croutons, with your choice of dressing is the perfect topping for ourcolorful salad."},
    {id: 'sausage', name: 'Sausage Platter', price: '$25.00', image: '/images/sausage-platter.jpg', description:"Grilled Spanish chicken, beef and chicken Nurnberger sausage. Served with saurkraut homemade roasted mashed potato and mustard grain sauce."},
    {id: 'beer', name: 'Craft Beer', price: '$20.00', image: '/images/beer1.jpg', description: "Now is the best time in history to be a craft beer lover. Different kind of craft beers brewed from the best mom and pop breweries inthe U.S. and Europe"},
]